version: '3.9'

services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: my_postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: control_person
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-persons

volumes:
  postgres-data:

networks:
  app-persons:
    driver: bridge